### PR TITLE
Reintroduces flaky tests

### PR DESCRIPTION
**Pull request by vimemo**
# Description

Includes previously excluded flaky tests.

medic/medic-webapp#5038
medic/medic-webapp#4932
medic/medic-webapp#4908

# Review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://github.com/medic/medic-docs/blob/master/development/style-guide.md), documented if necessary.
- [ ] Documented: Announced in Changes.md in plain English. Configuration and user documentation on [medic-docs](https://github.com/medic/medic-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in Changes.md.

# License

The software is provided under AGPL-3.0. Contributions to this project are accepted under the same license.

### CODE REVIEW

**Comment by vimemo** [comment]
@garethbowen, please review. I am unable to reproduce the previous issues with the latest code.

**Comment by garethbowen** [comment]
@vimemo How many times have you run the build on travis to prove it cannot be reproduced?

**Comment by vimemo** [comment]
@garethbowen, it should be 4 after this last travis-check.

**Comment by garethbowen** [comment]
I think around 20 successful builds would be enough to convince me. Can you make 20 commits with only whitespace changes so we can confirm before destabilising master again?

**Comment by vimemo** [comment]
hi @garethbowen, please review. Here are 26 runs with only a couple of failures that are not related to the three re-introduced tests. Each of the runs above includes a push-run and pr-run, the failures are related to pr-runs: one purge-login test failure and another about some send-message test; unrelated to the three tickets in this pr.

**Comment by vimemo** [comment]
@garethbowen, cool. yeah, the failure for that commit is [here](https://travis-ci.org/medic/medic-webapp/jobs/482824303); something related to "Purging on login Logging....". 
We will find out pretty soon if they are still failing, thanks for merging.

**Pull request merged**
