### PR TITLE
Fiddle javascript concatenation to fit appcache file size limits in c…

### PR DESCRIPTION
**Pull request by alxndrsn**
…hrome

Fix for follow-up bug in #1009.

In Incognito more in Chrome, there appears to be a size limit per file of
1310720 bytes.  To fix this, templates and other some bower components are
separated from the main `inbox.js` file into two separate files (one to be
loaded before `inbox.js`, and one after).

Also, template HTML is minified to remove whitespace before being compiled into
javascript.  Some care has to be taken - the minifier hangs if fed quotes-within
quotes, e.g. in the following line that this commit removes from
`feedback_admin.html`:

	<textarea name="feedback" placeholder="{@translate value="Bug description"/}"></textarea>

### CODE REVIEW

**Comment by garethbowen** [comment]
Do not use `--force`. It means the build won't fail on any error including unit test failures. Revert that commit and fix the bug.

**Comment by garethbowen** [comment]
Furthermore, can we call the file something better than "stuff"?

**Comment by alxndrsn** [comment]
I already suggested that it needs to be renamed.

**Comment by alxndrsn** [comment]
Ref fixing use of `--force`, as far as I can tell it's bizarre embedded dust.js directives that are causing it.  I've not looked at these templates before so would welcome your suggestion on what the correct fix would be.

**Comment by garethbowen** [comment]
Revert `--force` and we'll talk. Sorry I missed where you said it needed renaming.

**Comment by alxndrsn** [comment]
```Warning: Parse Error: <option value="0" {@eq key="hours" value="0"}selected="true"{/eq}>00</option>
``` for starters

**Pull request merged**
