### PR TITLE
added color for clients and server to architecture diagram.

### PR DESCRIPTION
**Pull request by mandric**

### CODE REVIEW

**Comment by estellecomment** [comment]
❤️  Thanks! I'd run out of patience trying to find svg-editing software, but it's nice as an SVG.

**Comment by mandric** [comment]
The big open source one is inkspace but there are many, you can also just read the spec and edit it! lol

**Comment by mandric** [comment]
Sucks that github can't embed svg images into markdown.  Leaving the path as-is for now since even though github doesn't render it, it's correct and works locally.

**Comment by estellecomment** [comment]
Hmm. I get the point of getting documentation to work offline, but I only check it online. I don't have a md file viewer offline.
So I wouldn't favor breaking the online version over the offline one.

**Pull request merged**
