### PR TITLE
Create db_schema.md

### PR DESCRIPTION
**Pull request by estellecomment**

### CODE REVIEW

**Comment by mandric** [comment]
The diagrams here don't take into account `national_office` type which I believe is technically still supported?  I believe we support 4 levels of places currently.

**Comment by mandric** [comment]
Also doesn't `docs/` make more sense than `doc/`?

**Comment by estellecomment** [comment]
@mandric 
 - Filed https://github.com/medic/medic-projects/issues/1278 to investigate the situation about `national_office`.
 - Got kinda lazy about renaming the `doc`->`docs` folder, especially since it's likely to break links in pages... How strongly do you care about this?

**Comment by mandric** [comment]
I don't think a `doc` rename is a big deal since the directory hasn't even existed for a month?  I'm happy to make the change if you'd rather move on.

**Comment by mandric** [comment]
Also would be cool to make these images SVGs.

**Pull request merged**
