### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by SCdF**
Getting rid of comments about Lucene, which we no longer use.

### CODE REVIEW

**Comment by SCdF** [comment]
@garethbowen: all good?

**Comment by garethbowen** [comment]
We still use lucene but it's an optional extra.

**Comment by estellecomment** [comment]
We use Lucene for the analytics page in 0.4. So it's still needed for running legacy code...

**Comment by SCdF** [comment]
@estellecomment right, but those people would hopefully be checking out the README associated with the 0.4 codebase.

As an update to this, I'm talking to Gareth about how to rewrite this to make it clearer what you do and do not need, when and why.

**Comment by SCdF** [comment]
Closed in favour of #2497.

**Pull request closed without merging**
