### PR TITLE
Wait for ages in e2e tests so builds don't break as frequently

### PR DESCRIPTION
**Pull request by alxndrsn**
Make e2e test timeout longer

### CODE REVIEW

**Comment by garethbowen** [comment]
I don't like just extending the timeout throughout.

Firstly I'm not sure if it'll actually help - in my experience most of the time a timeout occurs is because something didn't show on the screen and it never will. This change will just mean it waits longer for something that's not going to happen.

Secondly, if it's taking longer than 10 seconds to render something simple then we have a serious performance problem which we should look at.

Do you have high confidence this will work or are you just giving it a crack?

**Comment by alxndrsn** [comment]
> if it's taking longer than 10 seconds to render something simple then we have a serious performance problem

In my experience webdriver is unreasonably slow, so it's not useful to consider 10 seconds in a test as the same as 10 seconds for a real user.

> Do you have high confidence this will work or are you just giving it a crack?

Medium, currently.  I can keep pushing random stuff to this branch for a couple of days and see if we get any breakages.

**Comment by alxndrsn** [comment]
Failure:
```
Failures:
1) registration transition submits new sms messages shows content
  Message:
[31m    Expected 'R' to be 'Registration'.[0m
  Stack:
    Error: Failed expectation
        at checkItemSummary (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/registration-by-sms.js:222:84)
        at Object.it (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/registration-by-sms.js:250:7)
        at /home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:112:25
        at new ManagedPromise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1067:7)
        at ControlFlow.promise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2396:12)
        at schedulerExecute (/home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:95:18)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2860:25)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)

45 specs, 1 failure
```
– https://travis-ci.org/medic/medic-webapp/jobs/267482302

**Comment by alxndrsn** [comment]
Failure:
```
The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).
```
– https://travis-ci.org/medic/medic-webapp/jobs/267482302

**Comment by alxndrsn** [comment]
Failure:
```
Failures:
1) Add new person tests :  should add new person
  Message:
[31m    Expected 'http://localhost:5998/medic-test/_design/medic/_rewrite/#/contacts/d518ac1b-6019-4935-a01b-ca7220579fa9' to equal 'http://localhost:5998/medic-test/_design/medic/_rewrite/#/contacts/'.[0m
  Stack:
    Error: Failed expectation
        at Object.it (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/contacts/add-new-person.js:17:35)
        at /home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:112:25
        at new ManagedPromise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1067:7)
        at ControlFlow.promise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2396:12)
        at schedulerExecute (/home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:95:18)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2860:25)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at <anonymous>

45 specs, 1 failure
```
– https://travis-ci.org/medic/medic-webapp/jobs/267482333

**Comment by alxndrsn** [comment]
Failure:
```
The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).

The job has been terminated
```
– https://travis-ci.org/medic/medic-webapp/jobs/267482334

**Comment by alxndrsn** [comment]
Failure:
```
Failures:
1) Add new person tests :  should add new person
  Message:
[31m    Expected 'http://localhost:5998/medic-test/_design/medic/_rewrite/#/contacts/2ff349ff-db92-4fc9-b1b4-1ea4bd1738d5' to equal 'http://localhost:5998/medic-test/_design/medic/_rewrite/#/contacts/'.[0m
  Stack:
    Error: Failed expectation
        at Object.it (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/contacts/add-new-person.js:17:35)
        at /home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:112:25
        at new ManagedPromise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1067:7)
        at ControlFlow.promise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2396:12)
        at schedulerExecute (/home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:95:18)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2860:25)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at <anonymous>

45 specs, 1 failure
```
– https://travis-ci.org/medic/medic-webapp/jobs/267482432

**Comment by alxndrsn** [comment]
Failure:
```
docker: error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/18/182a46ef7ce6226ffd0c63bba5f8525638bd2fbb26fb94b1d6a4d10fa3c526eb/data?Expires=1503480665&Signature=Lgpit8eX2~Jc1cPxZCeqFBl3Q82BuZ4tXFyisgkGwMgE3U28KZi0UdJXa2H190XNELFF65mmMLyZT-vi8TVSGuSzZU152dI-QPq~z~BdjviRkfsBnMRTMNgtamWYgWlFMGF0HMObluGdI34FJj0lWlZ~JXbwmEU4wImt3z1xTxY_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp: lookup dseasb33srnrn.cloudfront.net on 169.254.169.254:53: read udp 10.10.23.203:53023->169.254.169.254:53: i/o timeout.

See 'docker run --help'.

Starting CouchDB 2.0
```
– https://travis-ci.org/medic/medic-webapp/jobs/267482502

**Comment by alxndrsn** [comment]
Failure:
```

Failures:
1) Add new person tests :  should add new person
  Message:
[31m    Expected 'http://localhost:5998/medic-test/_design/medic/_rewrite/#/contacts/1ba594e1-9fd8-4da8-ba5c-f06be4935597' to equal 'http://localhost:5998/medic-test/_design/medic/_rewrite/#/contacts/'.[0m
  Stack:
    Error: Failed expectation
        at Object.it (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/contacts/add-new-person.js:17:35)
        at /home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:112:25
        at new ManagedPromise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1067:7)
        at ControlFlow.promise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2396:12)
        at schedulerExecute (/home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:95:18)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2860:25)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at <anonymous>

45 specs, 1 failure
```
– https://travis-ci.org/medic/medic-webapp/jobs/267482542

**Comment by alxndrsn** [comment]
Failure:
```
Failures:
1) Add new person tests :  should add new person
  Message:
[31m    Expected 'http://localhost:5998/medic-test/_design/medic/_rewrite/#/contacts/ab4872c4-48e1-4772-be88-1eb546187e23' to equal 'http://localhost:5998/medic-test/_design/medic/_rewrite/#/contacts/'.[0m
  Stack:
    Error: Failed expectation
        at Object.it (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/contacts/add-new-person.js:17:35)
        at /home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:112:25
        at new ManagedPromise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1067:7)
        at ControlFlow.promise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2396:12)
        at schedulerExecute (/home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:95:18)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2860:25)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at <anonymous>

45 specs, 1 failure
```
– https://travis-ci.org/medic/medic-webapp/jobs/267482549

**Comment by alxndrsn** [comment]
Failure:
```

Failures:
1) Add new person tests :  should add new person
  Message:
[31m    Expected 'http://localhost:5998/medic-test/_design/medic/_rewrite/#/contacts/ab4872c4-48e1-4772-be88-1eb546187e23' to equal 'http://localhost:5998/medic-test/_design/medic/_rewrite/#/contacts/'.[0m
  Stack:
    Error: Failed expectation
        at Object.it (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/contacts/add-new-person.js:17:35)
        at /home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:112:25
        at new ManagedPromise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1067:7)
        at ControlFlow.promise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2396:12)
        at schedulerExecute (/home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:95:18)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2860:25)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at <anonymous>

45 specs, 1 failure
```
– https://travis-ci.org/medic/medic-webapp/jobs/267482549

**Comment by alxndrsn** [comment]
Failure:
```
Failures:
1) Add new person tests :  should add new person
  Message:
[31m    Expected 'http://localhost:5998/medic-test/_design/medic/_rewrite/#/contacts/5fdd3846-62f6-4c1d-9c2b-230a38ba40e6' to equal 'http://localhost:5998/medic-test/_design/medic/_rewrite/#/contacts/'.[0m
  Stack:
    Error: Failed expectation
        at Object.it (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/contacts/add-new-person.js:17:35)
        at /home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:112:25
        at new ManagedPromise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1067:7)
        at ControlFlow.promise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2396:12)
        at schedulerExecute (/home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:95:18)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2860:25)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at <anonymous>

45 specs, 1 failure
```
– https://travis-ci.org/medic/medic-webapp/jobs/267482626

**Comment by alxndrsn** [comment]
Failure:
```
  24 passing (21s)

  1 failing

  1) migrations integration test framework should be able to match docs with or without a fixed ID:

     Error: Error creating medic_api_integration_tests__medic: The database could not be created, the file already exists.

    at tests/integration/migrations/utils.js:281:33

    at Request._callback (node_modules/nano/lib/nano.js:241:7)

    at Request.self.callback (node_modules/request/request.js:188:22)

    at Request.<anonymous> (node_modules/request/request.js:1171:10)

    at IncomingMessage.<anonymous> (node_modules/request/request.js:1091:12)

    at endReadableNT (_stream_readable.js:1059:12)

    at _combinedTickCallback (internal/process/next_tick.js:138:11)

    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

  

Warning: Task "mochaTest:integration" failed. Use --force to continue.
```
https://travis-ci.org/medic/medic-webapp/jobs/267485793

**Comment by alxndrsn** [comment]
Failure:
```
Failures:
1) Add new person tests :  should add new person
  Message:
[31m    Expected 'http://localhost:5998/medic-test/_design/medic/_rewrite/#/contacts/1fff6af9-fc01-4c6a-9b58-831a94d03260' to equal 'http://localhost:5998/medic-test/_design/medic/_rewrite/#/contacts/'.[0m
  Stack:
    Error: Failed expectation
        at Object.it (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/contacts/add-new-person.js:17:35)
        at /home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:112:25
        at new ManagedPromise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1067:7)
        at ControlFlow.promise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2396:12)
        at schedulerExecute (/home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:95:18)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2860:25)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at <anonymous>

45 specs, 1 failure
```
– https://travis-ci.org/medic/medic-webapp/jobs/267485783

**Comment by alxndrsn** [comment]
Failure:
```
14.36s$ npm --prefix api install

npm ERR! code EINTEGRITY

npm ERR! sha1-+rg/uwstjchfpjbEudNMdUIMbWU= integrity checksum failed when using sha1: wanted sha1-+rg/uwstjchfpjbEudNMdUIMbWU= but got sha1-ucinCe/Z1wyLh3SnHlFDG+MnhHU=. (540147 bytes)

npm ERR! A complete log of this run can be found in:

npm ERR!     /home/travis/.npm/_logs/2017-08-23T11_22_07_261Z-debug.log

The command "npm --prefix api install" failed and exited with 1 during .
```
– https://travis-ci.org/medic/medic-webapp/jobs/267485895

**Comment by alxndrsn** [comment]
Failure:
```

Failures:
1) registration transition submits new sms messages shows content
  Message:
[31m    Expected 'R' to be 'Registration'.[0m
  Stack:
    Error: Failed expectation
        at checkItemSummary (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/registration-by-sms.js:222:84)
        at Object.it (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/registration-by-sms.js:250:7)
        at /home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:112:25
        at new ManagedPromise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1067:7)
        at ControlFlow.promise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2396:12)
        at schedulerExecute (/home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:95:18)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2860:25)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)

45 specs, 1 failure
```
– https://travis-ci.org/medic/medic-webapp/jobs/267485903

**Comment by alxndrsn** [comment]
Failure:
```
Failures:
1) Add new person tests :  should add new person
  Message:
[31m    Expected 'http://localhost:5998/medic-test/_design/medic/_rewrite/#/contacts/4367efeb-74cd-42c5-9f85-a86e246dfa52' to equal 'http://localhost:5998/medic-test/_design/medic/_rewrite/#/contacts/'.[0m
  Stack:
    Error: Failed expectation
        at Object.it (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/contacts/add-new-person.js:17:35)
        at /home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:112:25
        at new ManagedPromise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1067:7)
        at ControlFlow.promise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2396:12)
        at schedulerExecute (/home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:95:18)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2860:25)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at <anonymous>

45 specs, 1 failure
```
– https://travis-ci.org/medic/medic-webapp/jobs/267485899

**Comment by alxndrsn** [comment]
Failure:
```
Failures:
1) Add new person tests :  should add new person
  Message:
[31m    Expected 'http://localhost:5998/medic-test/_design/medic/_rewrite/#/contacts/daf5355c-512f-4597-9b4a-6a79ad9cd0fa' to equal 'http://localhost:5998/medic-test/_design/medic/_rewrite/#/contacts/'.[0m
  Stack:
    Error: Failed expectation
        at Object.it (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/contacts/add-new-person.js:17:35)
        at /home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:112:25
        at new ManagedPromise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1067:7)
        at ControlFlow.promise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2396:12)
        at schedulerExecute (/home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:95:18)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2860:25)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at <anonymous>

45 specs, 1 failure
```
– https://travis-ci.org/medic/medic-webapp/jobs/267485871

**Comment by alxndrsn** [comment]
Failure:
```
Failures:
1) Add new person tests :  should add new person
  Message:
[31m    Expected 'http://localhost:5998/medic-test/_design/medic/_rewrite/#/contacts/55b28809-27f0-4a76-acd5-7c51ddbf1e62' to equal 'http://localhost:5998/medic-test/_design/medic/_rewrite/#/contacts/'.[0m
  Stack:
    Error: Failed expectation
        at Object.it (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/contacts/add-new-person.js:17:35)
        at /home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:112:25
        at new ManagedPromise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1067:7)
        at ControlFlow.promise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2396:12)
        at schedulerExecute (/home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:95:18)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2860:25)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at <anonymous>

45 specs, 1 failure
```
– https://travis-ci.org/medic/medic-webapp/jobs/267485852

**Comment by alxndrsn** [comment]
Failure:
```

The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).

The job has been terminated
```
– https://travis-ci.org/medic/medic-webapp/jobs/267485990

**Comment by alxndrsn** [comment]
Failure:
```
Failures:
1) Add new person tests :  should add new person
  Message:
[31m    Expected 'http://localhost:5998/medic-test/_design/medic/_rewrite/#/contacts/2d946fe9-49a2-4e32-a2ef-de7a1aab4203' to equal 'http://localhost:5998/medic-test/_design/medic/_rewrite/#/contacts/'.[0m
  Stack:
    Error: Failed expectation
        at Object.it (/home/travis/build/medic/medic-webapp/tests/protractor/e2e/contacts/add-new-person.js:17:35)
        at /home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:112:25
        at new ManagedPromise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:1067:7)
        at ControlFlow.promise (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2396:12)
        at schedulerExecute (/home/travis/build/medic/medic-webapp/node_modules/jasminewd2/index.js:95:18)
        at TaskQueue.execute_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2970:14)
        at TaskQueue.executeNext_ (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2953:27)
        at asyncRun (/home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:2860:25)
        at /home/travis/build/medic/medic-webapp/node_modules/selenium-webdriver/lib/promise.js:676:7
        at <anonymous>

45 specs, 1 failure
```
– https://travis-ci.org/medic/medic-webapp/jobs/267485981

**Comment by alxndrsn** [comment]
Failure:
```
$ git checkout -qf 05efcedfd31b408ad4d764bf0ea4ecf3f41074ed

fatal: reference is not a tree: 05efcedfd31b408ad4d764bf0ea4ecf3f41074ed

The command "git checkout -qf 05efcedfd31b408ad4d764bf0ea4ecf3f41074ed" failed and exited with 128 during .

Your build has been stopped.
```
– https://travis-ci.org/medic/medic-webapp/jobs/267540866

**Comment by alxndrsn** [comment]
Failure:
```
fatal: reference is not a tree: 05efcedfd31b408ad4d764bf0ea4ecf3f41074ed

The command "git checkout -qf 05efcedfd31b408ad4d764bf0ea4ecf3f41074ed" failed and exited with 128 during .

Your build has been stopped.
```
– https://travis-ci.org/medic/medic-webapp/jobs/267540865

**Pull request closed without merging**
