### PR TITLE
#1762 - no letters in phone numbers

### PR DESCRIPTION
**Pull request by estellecomment**
https://github.com/medic/medic-webapp/issues/1762

See the tests for what is valid or invalid. 
This follows what libphonenumber does : allow any dots, dashes, spaces, but not other punctuation, and not letters.

Please advise on whether this would break existing instances, if users already saved invalid phone numbers for instance.

### CODE REVIEW

**Comment by estellecomment** [comment]
Note : this PR doesn't changed how clients are using libphonenumber (out of scope)

For instance, phone-widget.js will save an unformatted version of phone numbers. (e.g. save '777 888 999', as opposed to formatted : '+254777888999'). If that's an issue, we can file it separately.

**Comment by mandric** [comment]
This does change the API because libphonenumber.format() will now return false if the number is invalid rather than formatting a bad number.  This makes sense because we don't want to format/normalize a bad number.  If you want to save and format/normalize a bad number then don't use libphonenumber.

**Comment by mandric** [comment]
Yes @estellecomment also agree we should file an issue for the phone-widget.js problem.

**Comment by estellecomment** [comment]
Filed https://github.com/medic/medic-webapp/issues/1770

**Pull request merged**
