### PR TITLE
1395 select 2

### PR DESCRIPTION
**Pull request by alxndrsn**
@madric please review!

Known/suspected issues:

* facility selecter does not reset to blank when creating a new user in Config section
* sending message to multiple recipients may or may not work as expected (seems a bit weird to me, but i haven't checked the old behaviour)
* enketo db-selecters are a little bit hacky right now (inline changing of `<input>` to `<select>`)
* CSS may not look like it used to (poss missing bootstrap sylings)

### CODE REVIEW

**Comment by mandric** [comment]
Selecting a recipient in the send message drop down fails to validate.
screen shot 2015-11-04 at 10 36 05 am

**Comment by mandric** [comment]
The select2 return values appear correct though.  somehow validation was broken? 
```
$('#send-message [name=phone]').val()
["eeb17d6d-5dde-c2c0-62c4a1a0ca17fd17", "eeb17d6d-5dde-c2c0-62c4a1a0ca17fd16"]
```

**Comment by mandric** [comment]
Also getting an exception here:
screen shot 2015-11-04 at 10 47 09 am

**Comment by alxndrsn** [comment]
@mandric are you sure Paul's number is actually valid?

**Comment by alxndrsn** [comment]
When do you get that exception, and for which dropdown?

**Comment by mandric** [comment]
Pauls number is not valid... doesn't help that our demo data is invalid. trying a new one...
```
libphonenumber.validate(settings, '+28689170467')
false
```

**Comment by mandric** [comment]
After submitting a message, modal is not properly re-initialized.  Previous contact should not appear and Send button is still Sending...
screen shot 2015-11-04 at 11 05 23 am

**Comment by alxndrsn** [comment]
> After submitting a message, modal is not properly re-initialized. Previous contact should not appear and Send button is still Sending...

This is similar to the issue I mentioned in the OP: 

> facility selecter does not reset to blank when creating a new user in Config section

**Comment by mandric** [comment]
You prefer to have it in a separate issue?

**Comment by mandric** [comment]
Can't enter a manual phone number in the To field on Send Message modal, once you leave the field the phone number or any data you typed in is gone.  Pretty sure this is a a regression but  we can open new issues for any of these if your prefer Alex.

**Comment by mandric** [comment]
Code looks good here, wanted to avoid using the ugly boilerplate of the `dataAdapter` option but maybe can leave that for a refactor.  Merging so we can get on with more testing, mainly confirm this improves the experience on the mobile device.

**Pull request merged**
