### PR TITLE
Fix for #921 Full-text search: Places not indexed in Reports tab

### PR DESCRIPTION
**Pull request by alxndrsn**
Add the clinic name to full-text index used for searching data_records.

Fix for issue #921

### CODE REVIEW

**Comment by browndav** [comment]
Looks good to me.

One possible addition: should we type-check `doc.related_entities` before accessing it, just in case a document manages to get in with `related_entities` missing or set to a non-object?

**Comment by alxndrsn** [comment]
We dereference `related_entities` unsafely already at https://github.com/medic/medic-webapp/blob/921_include-clinic-name-in-full-text-search/lib/fulltext.js#L66, and possibly other places.  Happy to wrap the lot in an `if` block if that's deemed useful.

**Comment by browndav** [comment]
Or even just use a temporary and type-check/assign-an-empty-object to that. But yeah, we should check it one way or another.

**Comment by alxndrsn** [comment]
@browndav what does this need to get merged?

**Comment by browndav** [comment]
Nothing; looks good to me. Merge away.

**Comment by alxndrsn** [comment]
woohoo!

**Comment by alxndrsn** [comment]
who gets to close the issue?

**Comment by browndav** [comment]
The Github merge robot, it seems.

**Pull request merged**
