### PR TITLE
Remove unused templates?

### PR DESCRIPTION
**Pull request by alxndrsn**
Can't see these files are used anywhere.

### CODE REVIEW

**Comment by alxndrsn** [comment]
@mandric perhaps you know what these templates are for?

**Comment by mandric** [comment]
I do not recognize these templates @alxndrsn.

**Comment by alxndrsn** [comment]
References apparently removed in b8d694331c423b1038c3f6d3de2be69071a0749a

**Comment by alxndrsn** [comment]
# GREP
```
$ git grep -E '(locale|time).html'
$
```
# PICKAXE

```
$ git log -S 'locale.html'
commit b8d694331c423b1038c3f6d3de2be69071a0749a
Author: Gareth Bowen <gareth@bowenwebdesign.co.nz>
Date:   Wed Feb 3 14:39:01 2016 +1300

    Remove schedules config page. Issue: #1861

    Reduce ddoc size by cleaning up dependencies and moving kanso unit tests to /tests so they're not distributed with the app.

commit 90acec10e1e38ebdcf7d6b381899fb8a83e0c3be
Author: Gareth Bowen <gareth@bowenwebdesign.co.nz>
Date:   Fri Dec 19 10:56:51 2014 +1300

    Port settings and translations admin screens to angular. Hide admin tour until it gets reworked. Clear settings cache when settings are updated. Issue: #737

commit 07fa300cbf568d492ef22d03d6932562cd577548
Author: Gareth Bowen <gareth@bowenwebdesign.co.nz>
Date:   Tue May 27 16:01:57 2014 +1200

    When adding or removing locales on the settings page, the locale selector on the translations page is updated. Issue: #484

commit 7abc8e87709814357a4c22ff6774a10fa75474cc
Author: Gareth Bowen <gareth@bowenwebdesign.co.nz>
Date:   Wed May 7 11:52:13 2014 +1200

    Generify the rendering somewhat so new forms can be added easily. Issue: #487

commit f308ba6fd6089b7c865375eec931026682677fae
Author: Gareth Bowen <gareth@bowenwebdesign.co.nz>
Date:   Wed May 7 09:18:05 2014 +1200

    Translations defaults to system language. Issue: #484

commit 79882896b9186e18666c17ef1d503c63f430674e
Author: Gareth Bowen <gareth@bowenwebdesign.co.nz>
Date:   Wed May 7 08:38:33 2014 +1200

    Removed redundant prefix on template names. Issue: #487

commit cf3bdc14b11bacf95b99a2bf424944aa05b4873d
Author: Gareth Bowen <gareth@bowenwebdesign.co.nz>
Date:   Tue May 6 15:28:36 2014 +1200

    Added ability to add messages in any system language. Issue: #487
```

```
$ git log -S 'time.html'
commit b8d694331c423b1038c3f6d3de2be69071a0749a
Author: Gareth Bowen <gareth@bowenwebdesign.co.nz>
Date:   Wed Feb 3 14:39:01 2016 +1300

    Remove schedules config page. Issue: #1861

    Reduce ddoc size by cleaning up dependencies and moving kanso unit tests to /tests so they're not distributed with the app.

commit 90acec10e1e38ebdcf7d6b381899fb8a83e0c3be
Author: Gareth Bowen <gareth@bowenwebdesign.co.nz>
Date:   Fri Dec 19 10:56:51 2014 +1300

    Port settings and translations admin screens to angular. Hide admin tour until it gets reworked. Clear settings cache when settings are updated. Issue: #737

commit 7abc8e87709814357a4c22ff6774a10fa75474cc
Author: Gareth Bowen <gareth@bowenwebdesign.co.nz>
Date:   Wed May 7 11:52:13 2014 +1200

    Generify the rendering somewhat so new forms can be added easily. Issue: #487

commit 79882896b9186e18666c17ef1d503c63f430674e
Author: Gareth Bowen <gareth@bowenwebdesign.co.nz>
Date:   Wed May 7 08:38:33 2014 +1200

    Removed redundant prefix on template names. Issue: #487

commit 57759012bd601134845405f8d2272d5efcef3341
Author: Gareth Bowen <gareth@bowenwebdesign.co.nz>
Date:   Tue May 6 13:03:54 2014 +1200

    Moved templates into subdirectory. Issue: #487

commit 9aa0259c2e0bece5479a02bfc77faa03d5de10a9
Author: Gareth Bowen <gareth@bowenwebdesign.co.nz>
Date:   Tue May 6 11:41:56 2014 +1200

    Updated workflow to use drop down for setting times. Issue: #487

commit b7f40bf637d12cf39a48d78410ef130ead4627dc
Author: Gareth Bowen <gareth@bowenwebdesign.co.nz>
Date:   Tue May 6 11:05:28 2014 +1200

    Updated settings to use drop down for setting times. Issue: #484
```

**Pull request merged**
