### PR TITLE
Add some basic enketo telemetry

### PR DESCRIPTION
**Pull request by SCdF**
Records:
 - Render time, from the controller being initiated to paint
 - User time, between render time and them hitting save
 - Save time, from them hitting save to us completing a save

### CODE REVIEW

**Comment by SCdF** [comment]
At the suggestion of @michaelkohn .

Example output:
image

**Comment by dianabarsan** [comment]
@SCdF ping?

**Comment by SCdF** [comment]
@dianabarsan I added the other two entry points.

Let me know what you think. I'm not sure if I'm scoping the names right, I wonder if it should start with `enketo` instead of it being the second part. Your thoughts welcomed!

**Comment by dianabarsan** [comment]
I think starting with `enketo` would be a good idea, makes it easier to search by telemetry type. 
Everything looks good! I'll leave this to you to merge, in case you wanna switch the scoping.

**Pull request merged**
