### PR TITLE
Update openrosa-xpath-evaluator to allow translation of dates

### LINKED ISSUE #3459: Add format-date-tr() to our custom xpath functions to support translations of days and months in xforms
Spawned from discussion here: https://github.com/medic/medic-projects/issues/2019

Currently, the ODK spec (and therefore, Collect and Enketo) always uses English when rendering `%a` and `%b` options. @alxndrsn suggests that for the short term we add a custom xpath function so that we can translate `%a` and `%b` options into the language in which the form is being rendered.

In the longer term, the hope is that ODK will accept this change into its spec: https://github.com/opendatakit/xforms-spec/issues/122

### PR DESCRIPTION
**Pull request by alxndrsn**
format-date() will now translate into the UI langauge

Closes #3459

### CODE REVIEW

**Comment by alxndrsn** [comment]
> Looks ok. I couldn't really follow the changes in enketo, but I take it the "date.dayofweek.3" format is one they specify?

No, we specify this.

> Have you tested this in a language other than English?

I will confirm this.

> It'd be nice to unit test this.

👍 What specifically do you suggest testing?

**Comment by garethbowen** [comment]
> No, we specify this.

Ok. Seems like a strange format but I guess if all we have is a single string to play with it'll do.

> What specifically do you suggest testing?

The date translation code. It's only a few lines but it's a little complex.

**Comment by alxndrsn** [comment]
> Seems like a strange format

Open to suggestions :slightly_smiling_face:

**Comment by alxndrsn** [comment]
Merged manually.

**Pull request closed without merging**
