### PR TITLE
Adds modal warning before starting upgrade

### PR DESCRIPTION
**Pull request by dianabarsan**
# Description

Clicking "Upgrade" in the "Configuration > Upgrade" instance UI
displays a warning modal, which needs to be confirmed in order to start
the upgrade process.

medic/medic-webapp#3887

# Review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://github.com/medic/medic-docs/blob/master/development/style-guide.md), documented if necessary.
- [ ] Documented: Announced in Changes.md in plain English. Configuration and user documentation on [medic-docs](https://github.com/medic/medic-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in Changes.md.

### CODE REVIEW

**Comment by garethbowen** [comment]
@dianabarsan Are you still working on this?

I think the build is ok but you will have to fix that conflict.

I think the translation content is ok... maybe rephrase it to "make sure the data has been backed up" - essentially someone should do it but it doesn't have to be the same person doing the upgrade.

**Comment by dianabarsan** [comment]
@garethbowen Conflict resolved and translation updated. Thanks!

**Comment by garethbowen** [comment]
@SCdF Can you rereview please?

**Comment by garethbowen** [comment]
Merged. We can tweak the translation text in PoE during AT.

**Pull request merged**
