### PR TITLE
Add day to end date so it's inclusive. Parse dates in UTC. Issue: 1104

### PR DESCRIPTION
**Pull request by garethbowen**

### CODE REVIEW

**Comment by pkaini** [comment]
Includes the start date but not the end date. For e.g. if August 10th-August 14th selected, will export data from August 10th-August 13th. 
@abbyad

**Comment by garethbowen** [comment]
@pkaini I believe this PR with fix the start date _and_ the end date issue mentioned in https://github.com/medic/medic-projects/issues/27

**Comment by mandric** [comment]
Can you please re-submit against v0.4 so we can do a final rc release (bit of testing)?  Also if we merge on master we'll get an auto-deploy to market so we need to merge into an rc branch first.

**Comment by mandric** [comment]
Merging to rc branch instead.

**Comment by mandric** [comment]
FYI @pkaini this fix (export dates) was released yesterday in v0.4.9, let us know if it works for you when you get a chance.  You may need to update your instance. Thanks!

**Comment by pkaini** [comment]
Works now. Thanks!

On Thu, Aug 27, 2015 at 6:41 PM, Milan Andric <notifications@github.com>
wrote:

> FYI @pkaini <https://github.com/pkaini> this fix (export dates) was
> released yesterday in v0.4.9, let us know if it works for you when you get
> a chance. You may need to update your instance. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/medic/medic-webapp/pull/1149#issuecomment-135414728>.
>



-- 
Join our community. Sign up for Medic Mobile's newsletter.
<http://medicmobile.us8.list-manage.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=a3129fc799&e=c511575255>

Prakriti Kaini | Project Manager Asia
Medic Mobile
<http://medicmobile.us8.list-manage.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=6911deb493&e=c511575255>
 (+977)9808109171
@Medic
<http://medicmobile.us8.list-manage2.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=95a573475f&e=c511575255>
 Facebook
<http://medicmobile.us8.list-manage.com/track/click?u=e5b07d2afb4b273eaff8e3c53&id=7282d6a45d&e=c511575255>

**Pull request closed without merging**
