### PR TITLE
Just want to see if this is caught by anything

### PR DESCRIPTION
**Pull request by SCdF**
One would hope that this was caught by tests

# Review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://github.com/medic/medic-docs/blob/master/development/style-guide.md), documented if necessary.
- [ ] Documented: Announced in Changes.md in plain English. Configuration and user documentation on [medic-docs](https://github.com/medic/medic-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in Changes.md.

### CODE REVIEW

**Comment by SCdF** [comment]
@garethbowen / @alxndrsn interested in your thoughts about this: do you think this should fail our testing suite?

**Comment by alxndrsn** [comment]
It should probably fail code review...

**Comment by garethbowen** [comment]
Yeah permissions are important enough to warrant test coverage IMO, particularly because we won't notice if we break this by accident. This could be e2e tested to be 100% sure.

One mistake I made setting up the server.js was allowing too much logic to end up here which makes it virtually impossible to unit test. I think ideally the server.js would just have the URL declared and then immediately hand off to a controller. This would make it trivial to unit test that permissions are checked correctly.

**Comment by SCdF** [comment]
Cool. Yeah my current thought is to write an integration test that runs through all of the apis and makes sure it can and can't perform them correctly

**Pull request closed without merging**
