### PR TITLE
Test if ddoc exists after initial replication.

### PR DESCRIPTION
**Pull request by dianabarsan**
# Description

Also, retry initial replication automatically 1 minute after each failure.

medic/medic-webapp#4741

# Review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://github.com/medic/medic-docs/blob/master/development/style-guide.md), documented if necessary.
- [ ] Documented: Announced in Changes.md in plain English. Configuration and user documentation on [medic-docs](https://github.com/medic/medic-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in Changes.md.

### CODE REVIEW

**Comment by dianabarsan** [comment]
Please review, @garethbowen . Thanks!

**Comment by dianabarsan** [comment]
I actually implemented it with a retry at some point, I was thinking of retrying some amount of times before quitting and going down the final `catch` path (where it displays the "something's wrong with your connection" and the `retry` button).
Do you think it would be better to keep trying ad infinitum? Or keep trying while increasing a delay between tries before displaying the message to the user (similar to what replication does)? Or keep trying for a fixed number of times?

**Comment by garethbowen** [comment]
I think just keep trying forever, but a backoff is a good idea so if the server isn't responding because it's overloaded we don't just keep hammering it. It doesn't have to be really sophisticated - maybe leave a minute between auto retries?

**Comment by dianabarsan** [comment]
So, you think this is alright? I thought about making bootstrap a callable function so we don't reload the whole page when retrying, but it felt like a little overkill.

**Pull request merged**
