### PR TITLE
RFC for cleaning up how we do routing

### PR DESCRIPTION
**Pull request by SCdF**
DO NOT MERGE THIS.

Quick thought process for how we could clean up routing to make it more readable.

### CODE REVIEW

**Comment by garethbowen** [comment]
Yeah that's pretty close to what I was thinking. It's a shame that the auth component has to allow a function and not just a string (or array of strings) - it really breaks the readability. Given that I'd still vote for moving the Auth component into the export controller, because the function to determine what permissions you need is only relevant to the export endpoint and no other. 

I'm used to the pattern of controllers checking auth as part of the request validation, for example, how we use angular routing).

The main thing from my perspective is if I see the app making a request to a URL I want to work out which code is being executed and it's not always easy because of the parameters in the URL itself so I want to be able to scan down an aligned list of URL patterns and ideally fit the whole router.js on one screen.

So instead of...

```js
route(app.get,
  '/api/v2/export/:type',
  req => (['national_admin', exportData.exportPermission(req.params.type)]),
  exportData.v2);
route(app.post,
  '/api/v2/export/:type',
  req => (['national_admin', exportData.exportPermission(req.params.type)]),
  exportData.v2);
```

I would much prefer...

```js
app.get ('/api/v2/export/:type', exportData.v2);
app.post('/api/v2/export/:type', exportData.v2);
```

**Comment by SCdF** [comment]
Yeah, I get that it's more readable. It doesn't do anything for re-use though. All those individual controllers, potentially incorrectly handling the auth error handling incorrectly!

Actually, I guess this is the time when we make auth return a promise, at least promise chains are _slightly_ less likely to cause problems

**Comment by garethbowen** [comment]
You can still have reuse, just expose your permission checking and responding logic as a function (maybe in the auth.js util?). The controllers can do whatever logic they need to work out what permissions should be applied and than call that function.

**Comment by garethbowen** [comment]
@SCdF Where are we at with this? Can it be deleted now?

**Pull request closed without merging**
