### PR TITLE
Adding response log

### PR DESCRIPTION
**Pull request by vimemo**
# Description

In our api, we currently log http requests only. This update logs responses too.

medic/medic-webapp#4622

# Review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://github.com/medic/medic-docs/blob/master/development/style-guide.md), documented if necessary.
- [ ] Documented: Announced in Changes.md in plain English. Configuration and user documentation on [medic-docs](https://github.com/medic/medic-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in Changes.md.

### CODE REVIEW

**Comment by vimemo** [comment]
@garethbowen, please review.

curl http://localhost:5984/api/info
The abouve curl request now logs the following:
::1 - - [19/Jun/2018:03:00:09 +0000] "GET /api/info HTTP/1.1" - - "-" "curl/7.54.0"
::1 - - [19/Jun/2018:03:00:09 +0000] "GET /api/info HTTP/1.1" 200 19 10.325 ms

express-request-id library:
I experimented with the express-request-id. This library allows us to include an ":id" to identify the request. I just noticed this other ticket #4470. We could remove the date from both req/res logs and use this id instead. what do you think?

bunyan library:
I also played with the bunyan library and some default/custom serializers to log requests & responses in a json format with custom fields. Don't know that we need this at the moment but just mentioning it here.

**Comment by garethbowen** [comment]
Good start.

I think you're right - we need to include some ID so we can pair up the request with the response. I think that library you found is overkill - it has configuration for all sorts including setting the header on the response which we don't want. Have a look at [this comment](https://github.com/expressjs/morgan/issues/40#issuecomment-62004614) for a simple way to do the same thing.

And yes, let's get rid of the date at the same time.

I think it's probably also worth changing the log configuration so we don't get so many empty fields on the request side. What about this...

```js
app.use((req, res, next) => {
  req.id = uuid.v4();
  next();
});
morgan.token('id', req => req.id);
app.use(morgan('REQ :id :remote-addr :remote-user :method :url HTTP/:http-version', {immediate: true}));
app.use(morgan('RES :id :remote-addr :remote-user :method :url HTTP/:http-version :status :res[content-length] :response-time ms'));
```

That adds the ID, removes the date, and uses a consistent format between request and response logging.

What do you think?

**Comment by vimemo** [comment]
@gareth, updated with your suggestions. thank you.

**Comment by garethbowen** [comment]
Nice.

**Pull request merged**
