### PR TITLE
Update enketo to latest release

### PR DESCRIPTION
**Pull request by alxndrsn**
Issue: #2989

Sadly have had to fork the latest enketo, but hopefully we will get the change upstreamed shortly.

### CODE REVIEW

**Comment by alxndrsn** [comment]
Nope, it's a fork of enketo 4.26.1: https://github.com/medic/enketo-core/blob/node-iteration-support/package.json#L5

**Comment by alxndrsn** [comment]
Also any tips on getting the shrinkwrap to your liking would be much appreciated.

**Comment by garethbowen** [comment]
Ugh, yeah I misread that enketo dependency, sorry.

Given that those shrinkwrap changes are probably actually due to changes in enketo, so go for the merge. Nice one!

**Comment by alxndrsn** [comment]
Woohoo!

**Pull request merged**
