### PR TITLE
Fixes call to config in sentinel schedules.

### PR DESCRIPTION
**Pull request by dianabarsan**
# Description

Instead of sending the `config` module, send the actual configs. 

medic/medic-webapp#4735

# Review checklist

- [ ] Readable: Concise, well named, follows the [style guide](https://github.com/medic/medic-docs/blob/master/development/style-guide.md), documented if necessary.
- [ ] Documented: Announced in Changes.md in plain English. Configuration and user documentation on [medic-docs](https://github.com/medic/medic-docs/)
- [ ] Tested: Unit and/or e2e where appropriate
- [ ] Internationalised: All user facing text
- [ ] Backwards compatible: Works with existing data and configuration or includes a migration. Any breaking changes documented in Changes.md.

### CODE REVIEW

**Comment by dianabarsan** [comment]
Please review, @SCdF . Thanks!

**Comment by garethbowen** [comment]
It looks like this bug has been around for some time. Do you know which versions are affected?

**Comment by dianabarsan** [comment]
Versions `2.15` onward, I believe.

**Comment by garethbowen** [comment]
Yeah... Would you mind raising an issue for it so we can track it and schedule it appropriately?

**Pull request merged**
