### PR TITLE
Remove CouchDB-Audit from webapp dependencies

### PR DESCRIPTION
**Pull request by SCdF**
Removing couchdb-audit because we no longer need it in medic-webapp.

### CODE REVIEW

**Comment by garethbowen** [comment]
Why do we need `feedback`? For a view or something?

**Comment by SCdF** [comment]
@garethbowen so if I remove feedback and then run `kanso clean`:
```
$ kanso clean
Building version tree...

The following directories will be REMOVED:
    packages/async
    packages/feedback
    packages/kanso-gardener
```

Then if I `grunt dev` I get:
```
Running "browserify:dist" (browserify) task
>> Error: Cannot find module 'feedback' from '/Users/scdf/Code/Medic/medic-webapp/static/js/controllers'
Warning: Error running grunt-browserify. Use --force to continue.
```

I haven't looked into it further, I also haven't looked into if I can remove async and gardener.

**Comment by garethbowen** [comment]
Ok, it's because it's _only_ bundled as a kanso package. I'll raise an issue to publish it to npm then we can remove the kanso dependency.

**Comment by SCdF** [comment]
I've changed this branch to just be removing couchdb-audit. I'm going to raise a separate ticket to make sure all Kanso dependencies are correct.

**Pull request merged**
