### PR TITLE
modified tasks UI to load form immediately under certain conditions.

### PR DESCRIPTION
**Pull request by mandric**
Issue: https://github.com/medic/medic-webapp/issues/1242

One problem is the form doesn't immediately load if you hit the task URL directly, it loads the description page.  I wasn't sure how to  call performAction from the updateTasks function.  The function isn't available on the $scope yet in the other controller.

### CODE REVIEW

**Comment by mandric** [comment]
I'm a bit clueless why [this test](https://github.com/medic/medic-webapp/blob/develop/tests/karma/unit/controllers/tasks.js#L33) would break from this commit.

**Comment by mandric** [comment]
Should we also add a test for this?

**Comment by browndav** [comment]
I think so; I'd probably at least unit test that it does the right thing with a zero-action, one-action, and two-action form.

**Comment by mandric** [comment]
Wondering a bit if TasksCtrl and TasksContentCtrl should be merged into one.  Is there a reason we have separate controllers here?  Then performAction could be referenced during initial load and tests could be in the same place.  Or maybe there is a better way...

**Comment by garethbowen** [comment]
They're separate so you can do things like select a different task and update the url and the right hand pane without reloading the entire left hand pane. It does make things a little tricky in places but I think it's still the right thing to do.

**Comment by mandric** [comment]
Oddly one job in that last build failed, but appears to be a race condition.  

```
Firefox 31.0.0 (Linux 0.0.0) Enketo service render leaves img wrapped if failed to load FAILED
    timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

**Pull request merged**
