### PR TITLE
Tests update

### PR DESCRIPTION
**Pull request by IgorProtsenkoOd**
Changes:
Moved functions to related page objects according to testing area; 
replaced hardcoded explicit waits with helper calls;
removed redundant (duplicated) waits for element.

Test logic is not changed.
Successfully tested on master codebase.

### CODE REVIEW

**Comment by newtewt** [comment]
👍  on moving things into the page objects instead of being in the tests. 

Only callout I have is about the timeouts on browser.wait calls. Some places it is 10, 12, and 15 seconds. If I'm reading the docs right the default is 30 and configurable by setting defaultTimeoutInterval in the conf. I think that the default would be more than enough wait time and might be even to much if we are considering any type of performance in e2e tests. Another thought would to have this set based on the environment/OS/browser that the tests are running on. For example running using travis with sauce labs(or equivalent ) is a bit slower than running on our local environments.  

https://www.protractortest.org/#/api?view=webdriver.WebDriver.prototype.wait

**Comment by IgorProtsenkoOd** [comment]
@newtewt 
Yes, there is default Timeout interval already set in config (which implicit waiting), but the thing you are probably is looking at is helper.waitFor... cals, which are explicit waits for some elements.
It has the upper hand in flow, and the reason why it's used sometimes is that there are some 'heavy' activities where 30 secs might not be enough.
And vice versa, if we know that some action has to be completed within 10 second (like it's defined in some tests), and it takes longer that might be a bug, and there's no sense to wait any longer.

Second part - yes, it's nice to set different timeouts based on env, but I'd rather do it in another PR, since this one is only about polishing things.

**Comment by newtewt** [comment]
I'm not super adamant about setting the timeouts to one value and if it becomes something we want to change it isn't a lot of work. 

Agreed about the second. I was going to edit and mention it might be something we do as another commit. 

Feel free to merge.

**Comment by IgorProtsenkoOd** [comment]
@garethbowen 
Fixed modules and jshint passes its check but build still fails on CI.

How can I debug this or at least see what's wrong this time?

When I navigate failed check for Travis I see only this:

gpg: Signature made Wed 23 May 2018 09:02:50 PM UTC using RSA key ID B6FF4DE3
gpg: BAD signature from "Yarn Packaging <yarn@dan.cx>"
> GPG signature for this Yarn release is invalid! This is BAD and may mean the release has been tampered with. It is strongly recommended that you report this to the Yarn developers.
The command "[[ -z "$USE_YARN" ]] || curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0" failed and exited with 1 during .


Doesn't look like any changes that I've made.

Please advice.

**Comment by garethbowen** [comment]
yarn sometimes fails to install for no good reason - I've restarted that build so hopefully it'll pass this time.

**Comment by garethbowen** [comment]
@IgorProtsenkoOd It's green this time so feel free to merge! Nice one.

**Pull request merged**
