### PR TITLE
Support binding to fields.patient_uuid

### PR DESCRIPTION
**Pull request by SCdF**
In some configurations the patient_id field holds the patient shortcode,
while the patient_uuid field holds the internal id.

For tasks and targets it's important that we know how to bind to the
UUID as well, because otherwise users may see bugs while offline. For
example, a task wouldn't close until the report that closes the task is
synced upwards, run through by Sentinel, and synced back down.

Less important for purging, but it's better that we keep the function
logic the same.

### CODE REVIEW

**Comment by SCdF** [comment]
Apologies @garethbowen if you could smash that like button one more time, this time I swear I'll merge it at the right time!

**Comment by garethbowen** [comment]
Ok, so I merged the purge, and now this is conflicting... Back to you?

**Comment by SCdF** [comment]
Damn, I was hoping it would magically work...

**Comment by SCdF** [comment]
Superseded by https://github.com/medic/medic-webapp/pull/5216

**Pull request closed without merging**
