### PR TITLE
Don't minify alpha and beta releases

### PR DESCRIPTION
**Pull request by SCdF**
Minification is the default, but if you want you can specify to not
do it. Currently set to alpha and beta to make debugging things easier,
because debugging is more important than performance in these stages.

### CODE REVIEW

**Comment by SCdF** [comment]
@garethbowen I'm going to merge this and just try it on alpha. It everything explodes we can revert.

**Comment by SCdF** [comment]
Well… that didn't actually seem to stop minifying. Interesting.

**Comment by garethbowen** [comment]
@SCdF I think this is a bad idea. The point of beta releases is to test the final before it goes final - minification is part of that test. We have had a couple of instances where minification broke the code and it was only found in regression testing. I can live with no minification on alpha if that solves your problem? Please revert this change...

FWIW it didn't work because that minify flag only minifies the kanso stuff which we basically don't use. To stop the inbox.js minification you'd have to change the Grunt script to not call `uglify`.

**Comment by SCdF** [comment]
@garethbowen cool I'll revert the whole thing, since it's not solving any problems. Would be nice to have alpha builds not uglify, I'll look into it.

**Pull request merged**
