### PR TITLE
Remove unstable e2e test

### PR DESCRIPTION
**Pull request by alxndrsn**
Issue: #5099

### CODE REVIEW

**Comment by SCdF** [comment]
@alxndrsn have you tested that this skips? I'm pretty sure because we use Jasmine for protractor tests you have to use [xdescribe and friends](https://jasmine.github.io/api/3.3/global.html#xdescribe)

**Comment by alxndrsn** [comment]
@dianabarsan I agree I should fix it, but for now it's going to give intermittent failures on `master`, so maybe best skipped.

**Comment by dianabarsan** [comment]
Guess we can close this, right? :)

**Comment by alxndrsn** [comment]
Replaced by https://github.com/medic/medic-webapp/pull/5106

**Pull request closed without merging**
